# Generated by Django 3.1.4 on 2022-08-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('category', models.CharField(choices=[('ROYAL', 'ROYAL'), ('TWIN', 'TWIN'), ('EXECUTIVE', 'EXECUTIVE'), ('CLASSIC', 'CLASSIC'), ('SUPER', 'SUPER')], max_length=10)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
